### PR TITLE
Documentation fixes.

### PR DESCRIPTION
**Pull request by perara**
I leave my 10 minutes of work here. Essentially I've structured the docs in a scalable way, decoupling the docs from AWS (why would one advocate for a specific cloud service??? Centralized decentralization? Please learn from others mistakes #[Facebook](https://www.nytimes.com/2021/10/04/technology/facebook-down.html)) 
Furthermore, I've made the install steps more compact. The user following a guide of such a simple setup will just copy-paste anyways, and the more steps you have, the higher chance of your user to mess up the order. 

Also, I've renamed the image to truebitprotocol/eth-server and the container's name to truebit-eth-service for scalability later on.

My explanation took me another 4 minutes, so we're now up to 14 minutes (15 by the time I press the create pull request button)

Have a good one, and do not hesitate to ping if there are any questions :)

### CODE REVIEW

**Comment by perara** [comment]
Was supposed to propose #15fcc92c in another PR, but I can just as well argue for an MIT license here. Good boys and girls use MIT licenses for plain text and bash scripts. Argument done.

**Comment by cshotton** [comment]
I think there's a mistaken assumption in some of the edits in this PR that truebit-eth-server is going to be distributed via the truebitprotocol Docker Hub account and that's not likely. This is a developer-focused set of scripts and Dockerfile that are provided explicitly for people to download and adjust to their liking, then build locally. Building it as an immutable image to be pulled from truebitprotocol's Docker Hub defeats that intent.

**Comment by perara** [comment]
Hi, I've certainly not seen anything that would lead to the assumption that this is poised towards being published at Docker Hub. However, I can go so far as to assume that docker hub never should contain software under the tag truebitprotocol/eth-server. Hence, the local repository is used and not the docker hub. It is nonetheless a trivial fix to revert back to the original, which is seen in the latest commit.

**Comment by cshotton** [comment]
Per, your edits to change the docker image name from truebit-eth-server to truebitprotocol/eth-server are problematic as they are going to force the docker client to try and pull from the Docker Hub truebitprotocol repository instead of the user's local repo in certain circumstances. We don't currently plan to host a copy of truebit-eth-server in the truebitprotocol repository, so this will result in a non-functional command for the user. It's not an appropriate change.

**Comment by perara** [comment]
You can consider the matter fixed as I've already reverted to the original _truebit-eth-server_ name for the images. However, I'm still curious how you could come to believe that this would break under _certain circumstances_. The only way this _could_ break is that if something was published under the same name on docker.hub, in which you've been clear to say that it won't. Even if you account for possible scenarios where you have misconfigured DNS or no network, the naming convention proposed should work regardless. The image would not build in this case anyway because it relies on truebitprotocol/truebit-eth from docker.hub, But you are correct in that it would attempt to check the docker hub, In which it should not find anything and use the local image thereafter.  

Below is a paste of a **functional** command sequence with truebitprotocol/eth-server as the image name on a clean DO droplet.
```
root@ubuntu-main:~# docker build -t truebitprotocol/eth-server https://github.com/TruebitProtocol/truebit-eth-server.git#main
Sending build context to Docker daemon  127.5kB
Step 1/6 : FROM truebitprotocol/truebit-eth:latest
latest: Pulling from truebitprotocol/truebit-eth
feac53061382: Pull complete
932eb497be44: Pull complete
d7fcd310828c: Pull complete
49c4e33cdeb9: Pull complete
70c9e451c294: Pull complete
00ae98729d06: Pull complete
75d9d5becdc5: Pull complete
2325cce088ed: Pull complete
8ff36ace488d: Pull complete
ff50123fdca8: Pull complete
78efd08663f9: Pull complete
dc22936c5d4c: Pull complete
64503536dafc: Pull complete
57a08c0357b7: Pull complete
1c8e02ab2a0d: Pull complete
85f572c521e4: Pull complete
149ee7935415: Pull complete
Digest: sha256:2772fd282323c2ace6368fea2bb817e50ed4d3ddc77c61335b24e3269440896a
Status: Downloaded newer image for truebitprotocol/truebit-eth:latest
 ---> f0812b7c2696
Step 2/6 : MAINTAINER truebit
 ---> Running in 238ccbad79d4
Removing intermediate container 238ccbad79d4
 ---> 04f43e931e63
Step 3/6 : RUN apt-get update && apt-get install -y dialog screen ; mkdir /root/logs ; echo "PS1='${debian_chroot:+($debian_chroot)}\u@\h(truebit-eth-server):\w\$ '" >> /root/.bashrc
 ---> Running in ff11445c0283
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2210 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2803 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [640 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2367 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [607 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1431 kB]
Fetched 10.3 MB in 2s (5409 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  byobu | screenie | iselect ncurses-term
The following NEW packages will be installed:
  dialog screen
0 upgraded, 2 newly installed, 0 to remove and 18 not upgraded.
Need to get 794 kB of archives.
After this operation, 2159 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 dialog amd64 1.3-20171209-1 [217 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 screen amd64 4.6.2-1ubuntu1.1 [577 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 794 kB in 0s (13.2 MB/s)
Selecting previously unselected package dialog.
(Reading database ... 25410 files and directories currently installed.)
Preparing to unpack .../dialog_1.3-20171209-1_amd64.deb ...
Unpacking dialog (1.3-20171209-1) ...
Selecting previously unselected package screen.
Preparing to unpack .../screen_4.6.2-1ubuntu1.1_amd64.deb ...
Unpacking screen (4.6.2-1ubuntu1.1) ...
Setting up dialog (1.3-20171209-1) ...
Setting up screen (4.6.2-1ubuntu1.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Removing intermediate container ff11445c0283
 ---> cb72d468cd75
Step 4/6 : ADD ./scripts /tbscripts
 ---> d80281502235
Step 5/6 : EXPOSE 4001 8080 8545 8546 30303
 ---> Running in a84dfbc80e12
Removing intermediate container a84dfbc80e12
 ---> becc645a9bbd
Step 6/6 : CMD bash /tbscripts/start.sh
 ---> Running in 83331f04f668
Removing intermediate container 83331f04f668
 ---> 5423dda4e060
Successfully built 5423dda4e060
Successfully tagged truebitprotocol/eth-server:latest
root@ubuntu-main:~# TP_MOUNTPOINT=$HOME'/truebit-docker'
root@ubuntu-main:~# docker run \
> --network host \
> --name truebit-eth-server \
> -v $TP_MOUNTPOINT/docker-clef:/root/.clef \
> -v $TP_MOUNTPOINT/docker-geth:/root/.ethereum \
> -v $TP_MOUNTPOINT/docker-ipfs:/root/.ipfs \
> --rm \
> -it \
> truebitprotocol/eth-server:latest /bin/bash
root@ubuntu-main(truebit-eth-server):/$```

**Comment by perara** [comment]
As it seems of little interest to you with external contribution, I feel it is appropriate to close this PR. However, it should stand as an excellent example to others to think twice before using precious minutes on contributions that go nowhere. 

One last suggestion before I depart is to disable pull requests and issue tracker to respect others' time and effort or explicitly state that donations are met with little energy or appreciation. Sadly I fear that this last contribution will only go into the long line of ignored feedback.

**Pull request closed without merging**
